import * as cdk from 'aws-cdk-lib';
import * as codepipeline from 'aws-cdk-lib/aws-codepipeline';
import * as codepipeline_actions from 'aws-cdk-lib/aws-codepipeline-actions';
import * as codebuild from 'aws-cdk-lib/aws-codebuild';
import * as codedeploy from 'aws-cdk-lib/aws-codedeploy';
import * as s3 from 'aws-cdk-lib/aws-s3';
import * as events from 'aws-cdk-lib/aws-events';
import * as targets from 'aws-cdk-lib/aws-events-targets';
import * as iam from 'aws-cdk-lib/aws-iam';
import { Construct } from 'constructs';

export interface PipelineProps {
  readonly sourceBucket: s3.Bucket;
  readonly buildProject: codebuild.Project;
  readonly deploymentGroup: codedeploy.ServerDeploymentGroup;
}

export class DeploymentPipeline extends Construct {
  public readonly pipeline: codepipeline.Pipeline;

  constructor(scope: Construct, id: string, props: PipelineProps) {
    super(scope, id);

    // Create artifacts
    const sourceOutput = new codepipeline.Artifact('SourceOutput');
    const buildOutput = new codepipeline.Artifact('BuildOutput');

    // Create the pipeline
    this.pipeline = new codepipeline.Pipeline(this, 'Pipeline', {
      pipelineName: 'nitro-attestation-pipeline',
      pipelineType: codepipeline.PipelineType.V2,
      restartExecutionOnUpdate: false,
    });

    // Source Stage - S3 (trigger: NONE — we use a custom EventBridge rule below)
    this.pipeline.addStage({
      stageName: 'Source',
      actions: [
        new codepipeline_actions.S3SourceAction({
          actionName: 'S3Source',
          bucket: props.sourceBucket,
          bucketKey: 'source/source.zip',
          output: sourceOutput,
          trigger: codepipeline_actions.S3Trigger.NONE,
        }),
      ],
    });

    // Custom EventBridge rule using native S3 EventBridge notifications
    // (requires eventBridgeEnabled: true on the bucket)
    // This matches the "Object Created" event type (not CloudTrail-based)
    new events.Rule(this, 'S3SourceTriggerRule', {
      ruleName: 'nitro-attestation-s3-source-trigger',
      eventPattern: {
        source: ['aws.s3'],
        detailType: ['Object Created'],
        detail: {
          bucket: { name: [props.sourceBucket.bucketName] },
          object: { key: [{ prefix: 'source/source.zip' }] },
        },
      },
      targets: [new targets.CodePipeline(this.pipeline)],
    });

    // Build Stage - CodeBuild
    this.pipeline.addStage({
      stageName: 'Build',
      actions: [
        new codepipeline_actions.CodeBuildAction({
          actionName: 'BuildEnclave',
          project: props.buildProject,
          input: sourceOutput,
          outputs: [buildOutput],
        }),
      ],
    });

    // Deploy Stage - CodeDeploy
    this.pipeline.addStage({
      stageName: 'Deploy',
      actions: [
        new codepipeline_actions.CodeDeployServerDeployAction({
          actionName: 'DeployToEC2',
          deploymentGroup: props.deploymentGroup,
          input: buildOutput,
        }),
      ],
    });

    // ==================== cdk-nag Acknowledgements ====================
    cdk.Validations.of(this).acknowledge({
      id: 'AwsSolutions-KMS5',
      reason: 'KMS key rotation out of scope for sample app',
    });
    cdk.Validations.of(this).acknowledge({
      id: 'AwsSolutions-S1',
      reason: 'Bucket logging out of scope for sample app',
    });

    // Granular IAM5 findings generated by CDK Pipeline L2 grant*() methods
    const region = cdk.Stack.of(this).region;
    const account = cdk.Stack.of(this).account;
    const artifactsBucketNode = this.pipeline.artifactBucket.node.defaultChild as cdk.CfnResource;
    const eifBucketNode = props.sourceBucket.node.defaultChild as cdk.CfnResource;
    const artifactsBucketLogicalId = cdk.Stack.of(this).getLogicalId(artifactsBucketNode);
    const eifBucketLogicalId = cdk.Stack.of(this).getLogicalId(eifBucketNode);

    const nagRules: Record<string, string> = {};
    const pipelineReason = 'CDK Pipeline L2 construct internally generates grant*() with wildcard actions; cannot scope further without rewriting L2';
    for (const appliesTo of [
      'Action::s3:Abort*',
      'Action::s3:DeleteObject*',
      'Action::s3:GetBucket*',
      'Action::s3:GetObject*',
      'Action::s3:List*',
      'Action::kms:GenerateDataKey*',
      'Action::kms:ReEncrypt*',
      `Resource::<${artifactsBucketLogicalId}.Arn>/*`,
      `Resource::<${eifBucketLogicalId}.Arn>/*`,
    ]) {
      nagRules[`AwsSolutions-IAM5[${appliesTo}]`] = pipelineReason;
    }
    cdk.Stack.of(this).node.addMetadata('aws:cdk:acknowledged-rules', nagRules);
  }
}
